### ISSUE TITLE
module 'felupe' has no attribute 'Hyperelastic'

### ISSUE THREAD

**Issue by KosVla** [adtzlr/felupe#499]
I am trying to reproduce the provided examples locally, using the provided notebooks & guidelines. I have created a virtual environment with the dependencies required based on the provided instructions, however, for the hyperelastic balloon inflation I keep getting the following issue when I am trying to create the material
umat = fem.Hyperelastic(fem.yeoh, C10=0.5, C20=0, C30=0) => module 'felupe' has no attribute 'Hyperelastic'

I have managed to somehow circumvent this by doing umat = fem.UserMaterialHyperelastic(fem.constitution.yeoh,C10=0.5,C20=0, C30=0) but I am not sure this is how it is meant to work. 

Am I missing something obvious or is this indeed a bug?

**Comment by adtzlr** [comment]
Hi, just a short comment on this although you have already closed the issue:

The link to the docs always refer to the latest main-branch of the Git-repository. Read the docs supports versions on docs - you are able to select the version you have installed. `Hyperelastic` is just a shorter name for `UserMaterialHyperelastic` to reduce typing. `Hyperelastic` was not yet available in the latest release.

With the git main-branch of FElupe, I don't get a continuation error for the [inflation example](https://felupe.readthedocs.io/en/latest/examples/inflation.html) as you described. However, if I switch to the hardcoded Neo-Hookean material formulation of FElupe `felupe.NeoHooke(mu=1.0)`, the continuation stops due to numeric errors. Automatic differentiation as used in `felupe.Hyperelastic(felupe.yeoh(C10=0.5, C20=0, C30=0)` seems to be much more stable here.
